# Generated by Django 3.1.3 on 2020-12-02 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0004_auto_20201202_0915'),
        ('teacher', '0002_pupilstoobjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupilstoobjects',
            name='pupils',
        ),
        migrations.AddField(
            model_name='pupilstoobjects',
            name='classes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pupils.class'),
        ),
    ]
