# Generated by Django 3.1.3 on 2020-12-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0004_auto_20201202_0915'),
        ('teacher', '0003_auto_20201202_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupilstoobjects',
            name='classes',
        ),
        migrations.AddField(
            model_name='pupilstoobjects',
            name='classes',
            field=models.ManyToManyField(null=True, to='pupils.Class'),
        ),
    ]
