# Generated by Django 3.1.3 on 2020-12-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_pupilstoobjects_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupilstoobjects',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
