# Generated by Django 3.1.3 on 2020-12-02 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_auto_20201202_1055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
