# Generated by Django 3.1.3 on 2020-11-30 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='pupils',
            name='pupile_class',
        ),
        migrations.AddField(
            model_name='class',
            name='pupile_class',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pupils',
            name='classes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pupils.class'),
        ),
    ]
