# Generated by Django 3.1.3 on 2020-12-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupils',
            name='date_of_birth',
            field=models.DateTimeField(),
        ),
    ]
