# Generated by Django 3.1.3 on 2020-12-01 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0002_auto_20201130_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='pupile_class',
            new_name='pupil_class',
        ),
    ]
