# Generated by Django 3.1.3 on 2020-12-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0002_auto_20201204_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupils',
            name='date_of_birth',
            field=models.DateTimeField(null=True),
        ),
    ]
