# Generated by Django 3.1.3 on 2020-12-02 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0003_auto_20201201_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupils',
            name='classes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pupils', to='pupils.class'),
        ),
    ]
